include Makefile.common

TARGET = 1ST_READ

OPTFLAGS=-O3 -fomit-frame-pointer -fno-delayed-branch -DDREAMCAST -Wall -Werror
KOS_ROMDISK_DIR = romdisk_boot
KOS_BASE = .
COMPILER_CC = emcc
COMPILER_INCLUDES = ../addons/libtari/include

all: complete

complete: build_develop

clean:
	-del -f $(TARGET).elf $(OBJS)
	-del -f $(TARGET).BIN
	-del -f assets/debug/*.pkg
	-del -r -f romdisk_boot
	-del -r -f filesystem
	-del -f romdisk.img

build_develop: $(OBJS) 
	emcc $(OBJS) -O2 -s TOTAL_MEMORY=100000000 -s USE_SDL=2 -s USE_SDL_IMAGE=2 \
	-L../addons/libtari/bin -ltari \
	--use-preload-plugins \
    --preload-file assets --preload-file assets/fonts@fonts --preload-file assets/debug@debug -o 1.html
	

TARI_INCLUDE = ../addons/libtari/include
include ../addons/libtari/Makefile.commonweb
