include Makefile.common

TARGET = 1ST_READ


OBJS = $(OBJS) routes/pukeroute/discolevel.o routes/pukeroute/invisiblemirklingslevel.o \
routes/pukeroute/limitedsightlevel.o routes/pukeroute/playforyoulevel.o \
routes/pukeroute/rotatelevel.o routes/pukeroute/shakelevel.o \
routes/pukeroute/textblockingviewlevel.o \
routes/pukeroute/simulationbreakdown1.o routes/pukeroute/simulationbreakdown2.o \
routes/pukeroute/simulationbreakdown3.o routes/pukeroute/simulationbreakdown4.o \
routes/pukeroute/simulationbreakdown5.o

OBJS = $(OBJS) routes/standardroute/standard.o routes/standardroute/standard1.o routes/standardroute/standard2.o \
routes/standardroute/standard3.o routes/standardroute/standard4.o routes/standardroute/standard5.o \
routes/standardroute/standard6.o routes/standardroute/standard7.o routes/standardroute/standard8.o \
routes/standardroute/standard9.o routes/standardroute/standard10.o


OPTFLAGS=-O3 -fomit-frame-pointer -fno-delayed-branch -DDREAMCAST -Wall -Werror
KOS_ROMDISK_DIR = romdisk_boot
KOS_BASE = .
COMPILER_CC = emcc
COMPILER_INCLUDES = ../addons/libtari/include

all: complete

complete: build_develop

clean:
	-del -f $(TARGET).elf $(OBJS)
	-del -f $(TARGET).BIN
	-del -f assets/debug/*.pkg
	-del -r -f romdisk_boot
	-del -r -f filesystem
	-del -f romdisk.img

build_develop: $(OBJS) 
	emcc $(OBJS) -O2 -s TOTAL_MEMORY=100000000 -s USE_SDL=2 -s USE_SDL_IMAGE=2 \
	-L../addons/libtari/bin -ltari \
	--use-preload-plugins \
    --preload-file assets --preload-file assets/fonts@fonts --preload-file assets/debug@debug -o 1.html
	

TARI_INCLUDE = ../addons/libtari/include
include ../addons/libtari/Makefile.commonweb